import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireME from '@/components/HireME';
import LightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0 md:pt-16 sm:pt-8">
                    <div className="flex items-center justify-between w-full">
                        <div className="w-1/2">
                            <Image
                                src={profilePic}
                                alt="prashlons"
                                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                            ></Image>
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="Turning Vision Into Reality With Code And Design."
                                className="!text-6xl !text-left mb-4 xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
                            />
                            <p className="my-4 text-base font-medium">
                                As a skilled full-stack developer, I am dedicated to turning ideas
                                into innovative web applications. Explore my latest projects and
                                articles, showcasing my expertise in React.js and web development.
                            </p>
                            <div className="flex items-center self-start mt-2 lg:self-center">
                                <Link
                                    href="dummy.pdf"
                                    target={'_blank'}
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark hover:border-dark border-2 border-solid border-transparent  dark:text-dark dark:bg-light hover:dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light"
                                    download={true}
                                >
                                    Resume <LinkArrow className={'w-6 ml-1'} />
                                </Link>
                                <Link
                                    href="mailto: prashlons@gmail.com"
                                    target={'_blank'}
                                    className="flex items-center ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                                >
                                    Contact
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <HireME />
                <div className="absolute right-8 bottom-8 inline-block w-24">
                    <Image src={LightBulb} alt="Codebuck" className="w-full h-auto"></Image>
                </div>
            </main>
        </>
    );
}
